config/routes.rb
MadeitFrontpage::Application.routes.draw do

  namespace :store do  namespace :manager do  namespace :policies do resources :payments end end end

  namespace :store do  namespace :manager do  namespace :policies do resources :deliveries end end end

  namespace :store do  namespace :manager do  namespace :indices do resources :statuses end end end

  namespace :store do  namespace :manager do  namespace :indices do resources :users end end end

  namespace :store do  namespace :manager do  namespace :indices do resources :guides end end end

  namespace :home do  namespace :categories do  namespace :products do  namespace :indices do resources :users end end end end

  namespace :home do  namespace :categories do  namespace :products do  namespace :indices do resources :shops end end end end

  namespace :home do  namespace :categories do  namespace :products do  namespace :indices do resources :carts end end end end

  namespace :home do  namespace :categories do  namespace :products do  namespace :indices do resources :likes end end end end

  namespace :home do  namespace :categories do  namespace :products do  namespace :indices do resources :policies end end end end

  namespace :home do  namespace :categories do  namespace :products do  namespace :indices do resources :descriptions end end end end

  namespace :home do  namespace :categories do  namespace :products do  namespace :indices do resources :photos end end end end

  namespace :home do  namespace :cart do  namespace :indices do resources :products end end end

  namespace :home do  namespace :cart do resources :fails end end

  namespace :home do  namespace :cart do resources :successes end end

  namespace :home do  namespace :cart do resources :information end end

  namespace :home do  namespace :cart do resources :indices end end

  namespace :stores do resources :reports end

  namespace :home do  namespace :categories do  namespace :products do resources :reports end end end

  namespace :home do  namespace :categories do  namespace :products do resources :indices end end end

  namespace :store do  namespace :manager do  namespace :messages do  namespace :folders do resources :messages end end end end

  namespace :store do  namespace :manager do  namespace :messages do resources :unreads end end end

  namespace :store do  namespace :manager do  namespace :messages do resources :reads end end end

  namespace :store do  namespace :manager do  namespace :messages do resources :folders end end end

  namespace :store do  namespace :manager do resources :messages end end

  namespace :store do  namespace :manager do resources :promotions end end

  namespace :store do  namespace :manager do resources :ads end end

  namespace :store do  namespace :manager do resources :statistics end end

  namespace :store do  namespace :manager do  namespace :products do resources :reviews end end end

  namespace :store do  namespace :manager do resources :reviews end end

  namespace :store do  namespace :manager do resources :orders end end

  namespace :store do  namespace :manager do  namespace :products do resources :adds end end end

  namespace :store do  namespace :manager do resources :products end end

  namespace :store do  namespace :manager do resources :policies end end

  namespace :store do  namespace :manager do resources :settings end end

  namespace :store do  namespace :manager do resources :indices end end

  namespace :store do resources :registers end

  namespace :store do  namespace :policies do resources :information end end

  namespace :store do  namespace :policies do resources :ads end end

  namespace :store do resources :policies end

  namespace :store do  namespace :indices do resources :products end end

  namespace :store do  namespace :indices do  resources :information  end  end

  namespace :store do  namespace :indices do  resources :ads  end  end

  namespace :store do  resources :indices  end

  namespace :home do  resources :stores  end

  namespace :home do  resources :promotions  end

  namespace :home do  resources :events  end

  namespace :home do  namespace :searches do  resources :ads  end  end

  namespace :home do  namespace :searches do  resources :products  end  end

  namespace :home do  namespace :searches do  resources :messages  end  end

  namespace :home do  namespace :categories do  resources :products  end  end

  namespace :home do  namespace :categories do  resources :subs  end  end

  namespace :home do  namespace :categories do  resources :categories  end  end

  namespace :home do  namespace :indices do  resources :ads  end  end

  namespace :home do  namespace :indices do  resources :shops  end  end

  namespace :home do  namespace :indices do  resources :categories  end  end

  namespace :home do  namespace :indices do  resources :products  end  end

  namespace :home do  namespace :indices do  resources :categories  end  end

  namespace :home do  resources :indices  end

  namespace :home do  resources :categories  end

  namespace :home do  resources :searches  end

end

app/models/home/cart/indices.rb
module Home::Cart::Indices
  def self.table_name_prefix
    'home_cart_indices_'
  end
end

app/models/home/cart/indices/product.rb
class Home::Cart::Indices::Product < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/home/categories/products/indices.rb
module Home::Categories::Products::Indices
  def self.table_name_prefix
    'home_categories_products_indices_'
  end
end

app/models/home/categories/products/indices/cart.rb
class Home::Categories::Products::Indices::Cart < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/home/categories/products/indices/description.rb
class Home::Categories::Products::Indices::Description < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/home/categories/products/indices/like.rb
class Home::Categories::Products::Indices::Like < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/home/categories/products/indices/photo.rb
class Home::Categories::Products::Indices::Photo < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/home/categories/products/indices/policy.rb
class Home::Categories::Products::Indices::Policy < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/home/categories/products/indices/shop.rb
class Home::Categories::Products::Indices::Shop < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/home/categories/products/indices/user.rb
class Home::Categories::Products::Indices::User < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/home/indices.rb
module Home::Indices
  def self.table_name_prefix
    'home_indices_'
  end
end

app/models/home/indices/ad.rb
class Home::Indices::Ad < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/home/indices/category.rb
class Home::Indices::Category < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/home/indices/product.rb
class Home::Indices::Product < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/home/indices/recently.rb
class Home::Indices::Recently < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/home/indices/shop.rb
class Home::Indices::Shop < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/store/indices.rb
module Store::Indices
  def self.table_name_prefix
    'store_indices_'
  end
end

app/models/store/indices/ad.rb
class Store::Indices::Ad < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/store/indices/delivery.rb
class Store::Indices::Delivery < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/store/indices/information.rb
class Store::Indices::Information < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/views/home/categories/products/indices/likes/_form.html.erb
<%= form_for(@home_categories_products_indices_like) do |f| %>
  <% if @home_categories_products_indices_like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home_categories_products_indices_like.errors.count, "error") %> prohibited this home_categories_products_indices_like from being saved:</h2>

      <ul>
      <% @home_categories_products_indices_like.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/home/categories/products/indices/likes/edit.html.erb
<h1>Editing home_categories_products_indices_like</h1>

<%= render 'form' %>

<%= link_to 'Show', @home_categories_products_indices_like %> |
<%= link_to 'Back', home_categories_products_indices_likes_path %>

app/views/home/categories/products/indices/likes/index.html.erb
<h1>Listing home_categories_products_indices_likes</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @home_categories_products_indices_likes.each do |home_categories_products_indices_like| %>
  <tr>
    <td><%= link_to 'Show', home_categories_products_indices_like %></td>
    <td><%= link_to 'Edit', edit_home_categories_products_indices_like_path(home_categories_products_indices_like) %></td>
    <td><%= link_to 'Destroy', home_categories_products_indices_like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Like', new_home_categories_products_indices_like_path %>

app/views/home/categories/products/indices/likes/new.html.erb
<h1>New home_categories_products_indices_like</h1>

<%= render 'form' %>

<%= link_to 'Back', home_categories_products_indices_likes_path %>

app/views/home/categories/products/indices/likes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_home_categories_products_indices_like_path(@home_categories_products_indices_like) %> |
<%= link_to 'Back', home_categories_products_indices_likes_path %>